# Generated by Django 4.1.5 on 2023-01-20 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20230119_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('profile_pic', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='resourses')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.comments')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('baseprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='members.baseprofile')),
                ('score', models.IntegerField()),
                ('bio', models.TextField()),
                ('resume', models.FileField(upload_to='resumes')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.course')),
            ],
            bases=('members.baseprofile',),
        ),
        migrations.CreateModel(
            name='UniversityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('score', models.PositiveIntegerField()),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.comments')),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.course')),
                ('professors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.professor')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('baseprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='members.baseprofile')),
                ('university', models.CharField(max_length=100)),
                ('enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.course')),
            ],
            bases=('members.baseprofile',),
        ),
    ]
