# Generated by Django 4.1.5 on 2023-01-20 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_baseprofile_comments_course_professor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
