# Generated by Django 4.1.5 on 2023-01-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_baseprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseprofile',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.RemoveField(
            model_name='baseprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='baseprofile',
            name='last_name',
        ),
    ]
