# Generated by Django 4.1.5 on 2023-01-20 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_comments_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityprofile',
            name='comments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='members.comments'),
        ),
        migrations.AlterField(
            model_name='universityprofile',
            name='courses',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='members.course'),
        ),
        migrations.AlterField(
            model_name='universityprofile',
            name='professors',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='members.professor'),
        ),
        migrations.AlterField(
            model_name='universityprofile',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
