# Generated by Django 4.1.5 on 2023-01-20 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_course_comment_alter_course_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityprofile',
            name='comments',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.comments'),
        ),
        migrations.AlterField(
            model_name='universityprofile',
            name='courses',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.course'),
        ),
        migrations.AlterField(
            model_name='universityprofile',
            name='professors',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.professor'),
        ),
    ]
