# Generated by Django 4.1.5 on 2023-01-20 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_alter_course_comment_alter_course_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='university',
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(default=None, max_length=160),
            preserve_default=False,
        ),
    ]
