# Generated by Django 4.1.5 on 2023-01-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_studentprofile_university_user_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
